Fix issue #1, #2
xteamstudio/nuxt-project-testing pull request #8
Opened 2019-04-19 01:32 UTC by teraui41

Thank you for your contribution to the develop branch of **nuxt-project-testing** repo.
 
Before submitting this PR, please make sure:

- [ ] Title should start with `Fix`, `Add`, `Modify`, `Setup`, `Implement`, etc...
- [ ] Code builds cleanly without any error or warning
- [ ] Methods and variables are using the approved terminology
- [ ] Test specs are added or updated accordingly
- [ ] Link this PR to a related issue

2019-04-19 02:35 UTC, echoulen commented on package.json
> -    "test": "nuxt build && TZ=Asia/Taipei jest",
should not remove `TZ=Asia/Taipei`

2019-04-19 02:35 UTC, echoulen commented on src/components/TreeComponent/TreeItem.vue
> +      hasChildren: function() {
`hasChildren() { ... } ` is better

2019-04-19 02:35 UTC, echoulen commented on tests/pages/index.spec.ts
> +import { findLabel } from "../../src/utils/findLabel";
wired format
```
import {mockPermissions} from ...
import { findLabel } from ...
```

2019-04-19 06:56 UTC, nelsliu9121 requested changes
幾個事情請在開發前先確認：

1. 檢查專案的書寫設定
  a. 檔案請以空白行結尾
  b. `import` 大括號不應該有空白間隔
  c. 不在物件宣告使用 `function`
  d. 縮排、空格應比照原設定（可依靠 `tslint`、`prettier` 協助）
2. 不任意修改對外 port 編號（或是不加入 commit）
3. 檔案取名應符合專案的習慣 （`TreeComponent/index.vue` 不合習慣）
4. 發出 Pull request 應該要檢查的項目也請一一確認勾選

2019-04-19 07:34 UTC, closed without merging

2019-04-22 01:57 UTC, teraui41 commented
謝謝！這些開發習慣未來我會多加注意，也謝謝您們的指教，受益良多．